services:
  - type: web
    name: reportagent
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ENVIRONMENT  
        value: production
      - key: PYTHONPATH
        value: /app
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 0
      maxInstances: 1