services:
  - type: web
    name: reportagent
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ENVIRONMENT  
        value: production
      - key: LOW_MEMORY_MODE
        value: "true"
      - key: ENABLE_VECTOR_DB
        value: "false"
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 0
      maxInstances: 1